base/urls.py
from django.urls import path
from .views import TaskList , TaskDetail , TaskCreate ,TaskUpdate , TaskDelete

app_name = 'base'

urlpatterns = [
    path('', TaskList.as_view(),name='tasks'),
    path('task/<int:pk>/',TaskDetail.as_view(), name = 'task'),
    path('task-create/',TaskCreate.as_view(), name = 'task-create'),
    path('task-update/<int:pk>/',TaskUpdate.as_view(), name = 'task-update'),
    path('task-delete/<int:pk>/',TaskDelete.as_view(), name = 'task-delete')
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls' , namespace= 'base')),
    path('user/',include('users.urls' , namespace = 'user'))
]

users/urls.py
from django.urls import path
from .views import customLoginView , RegisterPage
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns =[
    path('login/',customLoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(next_page = 'user:login'),name='logout'),
    path('register/',RegisterPage.as_view(), name = 'register')
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model) :
    user = models.ForeignKey(User,on_delete=models.CASCADE , null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        ordering = ['complete']

users/models.py
from django.db import models

# Create your models here.

base/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView ,UpdateView , DeleteView
from django.urls import reverse_lazy
from .models import Task
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class TaskList(LoginRequiredMixin,ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user = self.request.user)
        context['count'] = context['tasks'].filter(complete = False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__icontains = search_input)
        context['search_input'] = search_input
        return context

class TaskDetail(LoginRequiredMixin,DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'

class TaskCreate(LoginRequiredMixin,CreateView):
    model = Task
    fields = ['title','description','complete']
    success_url = reverse_lazy('base:tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate,self).form_valid(form)

class TaskUpdate(LoginRequiredMixin,UpdateView):
    model = Task
    fields = ['title','description','complete']
    success_url =  reverse_lazy('base:tasks')


class TaskDelete(LoginRequiredMixin,DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('base:tasks')
    template_name = 'base/task_delete.html'

users/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth import login

# Create your views here.
class customLoginView(LoginView):
    template_name = 'users/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('base:tasks')

class RegisterPage(FormView):
    template_name = 'users/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('base:tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request,user)
        return super(RegisterPage,self).form_valid(form)
    
    def get(self,*args,**kargs):
        if self.request.user.is_authenticated:
            return redirect('base:tasks')
        return super(RegisterPage,self).get(*args,**kargs)

base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do List</title>
    <style>
        body{
            background-color: rgb(231, 231, 235);
            font-family: 'Poppins', sans-serif;
            padding: 50px;
        }

        .container {
            max-width: 550px;
            background-color: #fff;
            margin : auto;
            
        }

        .header-bar{
            display: flex;
            justify-content: space-between;
            margin: auto;
            padding:10px;
            border-radius: 5px 5px 0 0;
            background-color: rgb(61, 123, 255);
            color: #fff;
        }
        .header-bar a{
            color:#fff;
            text-decoration: none;
        }

        .items{
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 20px;
            background-color: #fff;
            border-top: 1px solid rgb(226,226,226);

        }

        .task-title{
            display : flex;
        }

        .task-title a {
             text-decoration: none;
             color:rgb(59, 59, 59);
             margin-left: 10px;
        }

        .task-complete-icon{
            height:20px;
            width:20px;
            background-color: rgb(103, 204, 154);
            border-radius: 50%;
        }

        .task-incomplete-icon{
            height: 20px;
            width:20px;
            background-color: rgb(221, 221, 221);
            border-radius: 50%;
        }
        .delete-link{
            text-decoration: none;
            color: rgb(105, 15, 15);
            font-size: 22px;
            font-weight: 900;
        }

        #search-add-wrapper{
            display:flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
        }
        #add-link{
            color : rgb(61, 123, 255);
            text-decoration: none;
            font-size: 42px;
            text-shadow: 1px 1px  rgb(35, 79, 173); 
        }

        .button{
            border:1px solid rgb(61, 123, 255);
            background-color: #fafafa;
            color:rgb(61, 123, 255);
            padding: 10px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }


        input[type=text],
        input[type=password],
        textarea{
            border : 1px solid rgb(101, 101, 102);
            border-radius: 5px;
            padding:10px;
            width:90%;
        }

        label{
            padding-top: 10px important!;
            display: block;
        }



    </style>

     <link rel="preconnect" href="https://fonts.googleapis.com">
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet"> 
</head>
<body>
    <div class = "container">
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

base/templates/base/task.html
<h1>Task : {{task}}</h1>
<p>{{task.description}}</p>
<p>created : {{task.created}}</p>

base/templates/base/task_delete.html
{% extends 'base/main.html' %}
{% block content %}

<button>
    <a href ="{% url 'base:tasks' %}">Go Back</a>
</button>
<form method = 'POST'>
    {% csrf_token %}
    <p>Are you sure you want to delete the task ?"{{task}}"</p>
    <input type="submit" value ="delete">
</form>

{% endblock content %}

base/templates/base/task_form.html
{% extends 'base/main.html' %}
{% block content %}

<h1>Task Form</h1>

<form method="POST" action="">
    {% csrf_token%}
    {{form.as_p}}
    <input type ="submit" value = "submit">
</form>

{% endblock content %}

base/templates/base/task_list.html
   {% extends 'base/main.html' %}
   {% block content %}

   <div class = 'header-bar'>
       <div>
           <h1> Welcome {{request.user|title}}!</h1>
           <h3> <i>you have </i> {{count}} <i> incomplete item{{ count|pluralize:'s' }} </i></h3>
       </div>
        {% if request.user.is_authenticated %}
            <a href="{% url 'user:logout' %}"> Logout</a>
        {%else%}
            <a href="{% url 'user:login'%}">Login</a>
        {% endif %}
   </div>

    
    <div id = 'search-add-wrapper'>
        <form method = 'get' style="margin-top:20px;display : flex;">
            <input type = 'text' name = 'search-area' value = '{{search_input}}'>
            <input type = 'submit' value = 'search' class = 'button'>
        </form>
        <a href="{% url 'base:task-create' %}" id = add-link>&#x2b;</a>
    </div>

    <div class = 'task-wrapper'>
        {% for task in tasks %}
        <div class = items>
            {% if task.complete %}
            <div class = 'task-title'>
                <div class = "task-complete-icon"></div>
                <i><s><a href = "{% url 'base:task-update' task.id %}"> {{task}}</a></s></i>
            </div>
            
            {% else %}
            <div class = 'task-title'>
                <div class = "task-incomplete-icon"></div>
                <a href = "{% url 'base:task-update' task.id %}"> {{task}}</a>
            </div>
            
            {% endif%}
            <a class = "delete-link" href ="{% url 'base:task-delete' task.id %}">&#215;</a>
        </div>
        {% empty %}
        <h5>No items in the list!!</h5>
        {% endfor %}
    </div>

    {% endblock content %}

   
    

users/templates/users/login.html
{% extends 'base/main.html' %}
{% block content %}

<h1>Welcome! Please Login</h1>
<hr>
<form method = "post">
    {% csrf_token %}
    {{form.as_p}}
    <input type = "submit" value = "Login">
</form>

<p>Dont have an account? <a href="{% url 'users:register' %}">Register</a></p>

{% endblock content %}

users/templates/users/register.html
{% extends 'base/main.html' %}
{% block content %}

<h1>Welcome! Please Register</h1>
<hr>
<form method = "post">
    {% csrf_token %}
    {{form.as_p}}
    <input type = "submit" value = "Register">
</form>

<p>Already have an account? <a href="{% url 'users:login' %}">Login</a></p>

{% endblock content %}